### ISSUE TITLE
pyqtgraph issue[BUG]

### ISSUE THREAD

**Issue by AlexStox** [highfestiva/finplot#371]
### Requirements (place an `x` in each of the `[ ]`)**
* [x] I realize finplot is not a web lib. (Hint: it's native!)
* [x] I've read the [snippets](https://github.com/highfestiva/finplot/wiki/Snippets) and not found what I'm looking for.
* [x] I've searched for any related issues and avoided creating a duplicate issue.
* [x] I've updated finplot (`pip install -U finplot`).
* [x] I've supplied the required data to run my code below.

### Code to reproduce

```python
import pandas as pd
import finplot as fplt
df = pd.DataFrame({"open": [100, 105, 95, 99, 92],
                   "high": [110, 120, 115, 110, 115],
                   "low": [92, 90, 85, 70, 81],
                   "close": [105, 95, 99, 92, 85],
                   "volume": [10, 12, 5, 1, 15],
                   },
                  index=pd.date_range("2020-01-01", "2020-01-05"))
ax, ax2 = fplt.create_plot("XXX", rows=2)  # create two axes plot
cols_for_candles = ['open', 'close', 'high', 'low']
cols_for_volume = ['open', 'close', 'volume']
df_candles = df[cols_for_candles]
fplt.candlestick_ochl(df_candles, ax=ax)
df_volume = df[cols_for_volume]
fplt.volume_ocv(df_volume, ax=ax2)
fplt.show()
```

### Describe the bug
I've read topics in Discussions and Issues and there is one common issue among them - **pyqtgraph**. 
I have updated pyqtgraph to version 0.13.1 recently. And the version of finplot is 1.8.4. 
After the **pyqtgraph update** finplot doesn't work - I got this error whenever I run any code that worked fine previously before the update.
```
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'
```

### Expected behavior
There is no error while running finplot.

#### Screenshots
![image](https://user-images.githubusercontent.com/55058601/193252419-2007d67c-bc9a-43a3-897b-ce3b4ad955ba.png)

#### Reproducible in:

*OS*: windows 10
*finplot version*: 1.8.4
*pyqtgraph version*: 0.13.1
*pyqt version*: 5.15.7
*pyqt5-qt version*: 5.15.2
*pyqt5-sip version*: 12.11.0
*pyqt5webengine version*: 5.15.6

**Comment by mishell-trickster** [comment]
Got similar problem right now with QT `module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'. Did you mean: 'QGuiApplication'?`
Seems like problem with QT versioning or with which QT used under the hood of finplot.
Python: 3.10
QT Version: 5.15.5
OS: Manjaro Linux

**Comment by AlexStox** [comment]
I'm sure the issue is in pyqtgraph, because the bug appeared when I updated pyqtgraph (at that time other libraries were not updated). When I updated other libraries, the error still remains. Send like they changed the library

**Comment by highfestiva** [comment]
This might be a portability issue when they are doing adjustments for PyQt 6. I'll get to it some day soon, please keep this bug open.

**Comment by Etirf** [comment]
Hi, as it's been ~15 days
Here is a nasty workaround till it gets fixed:


directly in `__init__.py` :


Add at the start of the file ` PyQt5 import QtWidgets`
line 1835:  Replace `app = QtGui.QApplication.instance()` with `app = QtWidgets.QApplication.instance()`

**Comment by sunjar2020** [comment]
I had the same problem today,  when I upgraded python 3.79 to 3.86 and updated several libraries, I solved it using this method:

pip3 install pyqtgraph = = 0.12.4

From: https://github.com/AdaptiveParticles/pyapr/issues/68#issuecomment-1282409401

**Comment by Etirf** [comment]
> > directly in `__init__.py` :
> > Add at the start of the file ` PyQt5 import QtWidgets`
> 
> sorry, but in Python this kind of importing doesn't work (however I'm new to Python), did you mean `from PyQt5 import QtWidgets` ?
> 
> > line 1835: Replace app = QtGui.QApplication.instance() with app = QtWidgets.QApplication.instance()
> in what module should I do these changes?


Indeed, corrected the typo! 

To answer your question, default path should be something along the lines:
C:\Users\<username>\AppData\Local\Programs\Python\Python39\Lib\site-packages\finplot\__init__.py

**Comment by AlexStox** [comment]
> Transitioned to PyQt6 in [efb8696](https://github.com/highfestiva/finplot/commit/efb869668b2d0eb35e332eed5fce75f523b8ad0a).

should I just update finplot?

**Comment by highfestiva** [comment]
You need to update finplot, pyqtgraph, and pyqt5 and uninstall pyqt5.
